main:
  ==: org.bukkit.inventory.ItemStack
  v: 2578
  type: WRITTEN_BOOK
  meta:
    ==: ItemMeta
    meta-type: BOOK_SIGNED
    title: DefaultBook
    author: Srain3
    pages:
      - |-
        ServerNewsPLの使い方
        /oyasainews や /onewsで
        メインのお知らせを開きます。
        オプションは次のページ
      - |-
        -=[add] [BookName]=-
        このオプションは
        [BookName]という名前で
        本を保存するコマンドです
        [BookName]でmainを指定すると
        Join時に開く本を更新できます
        記入済みの本のみ保存します。
      - |-
        -=[open] [BookName]=-
        このオプションは
        [BookName]という名前で
        登録されている本を開くコマンド
        [BookName]にmainと入力すると
        オプション無しと同じです
        (メインのお知らせ表示する)
      - |-
        -=[booklist]=-
        このオプションは
        登録されてる本のリストを
        調べるコマンドです。
        コレに表示される名前を
        [BookName]に入れれば
        openやgetとremove出来ます
      - |-
        -=[get] [BookName]=-
        このオプションは
        [BookName]という名前で
        登録されている本を
        編集できる状態で取得するコマンド
      - |-
        -=[remove] [BookName]=-
        このオプションは
        [BookName]という名前で
        登録されている本の設定を
        消去するコマンドです。
        configから即消しなので注意
      - |-
        -=[setspawn]=-
        この非表示オプションは
        spawnする場所を登録して
        お初が入った時にお知らせを
        開かないように抑制するための
        設定するコマンドです。
        spawnする場所で打つだけで
        設定は完了します。
mainversion: 1