main:
  ==: org.bukkit.inventory.ItemStack
  v: 2578
  type: WRITTEN_BOOK
  meta:
    ==: ItemMeta
    meta-type: BOOK_SIGNED
    title: v1
    author: Srain3
    pages:
      - v1_デフォルトテスト用
mainversion: 1
playerdata: