name: Server-News
main: com.github.srain3.Main
version: "0.9.51"
api-version: "1.16"
author: Srain3
description: "お知らせ用の本を登録/入手できるプラグイン"
website: "https://github.com/Srain3/Server-News"

commands:
 oyasainews:
  usage: "/<command>"
  description: "おやさい鯖のお知らせ用コマンド"
  aliases:
    - onews