name: Server-News
main: com.github.srain3.Main
<<<<<<< Updated upstream
version: "1.2.1"
=======
version: "1.2.2"
>>>>>>> Stashed changes
api-version: "1.16"
author: Srain3
description: "お知らせ用の本を登録/入手できるプラグイン"
website: "https://github.com/Srain3/Server-News"
softdepend:
  - LuckPerms

commands:
 oyasainews:
  usage: "/<command>"
  description: "おやさい鯖のお知らせ用コマンド"
  permission: servernews.oyasainews
  permission-message: "No Permission!!!"
  aliases:
    - onews

permissions:
  servernews.oyasainews:
    description: "oyasainews デフォルト権限(みんな持ってる)"
    default: true
    children:
     servernews.oyasainews.open: true
     servernews.oyasainews.booklist: true
     servernews.oyasainews.color: true
  servernews.oyasainews.admin:
    description: "oyasainews admin権限"
    default: op
    children:
      servernews.oyasainews.add: true
      servernews.oyasainews.get: true
      servernews.oyasainews.remove: true
      servernews.oyasainews.setspawn: true
  servernews.oyasainews.open:
    default: true
  servernews.oyasainews.booklist:
    default: true
  servernews.oyasainews.color:
    default: true
  servernews.oyasainews.add:
    default: op
  servernews.oyasainews.get:
    default: op
  servernews.oyasainews.remove:
    default: op
  servernews.oyasainews.setspawn:
    default: op